---
AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'Berksfile'
    - 'Gemfile'
    - 'Rakefile'
    - 'test/**/*'
Documentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
NumericLiteralPrefix:
  Enabled: false
AbcSize:
  Enabled: false
CyclomaticComplexity: 
  Enabled: false
  